### ISSUE TITLE
Create a basic report template

### ISSUE THREAD

**Issue by Deepthi-Chand** [CivicDataLab/IDS-DRR#22]
Deadline 24 Jul
- [x] First round - Brainstorm elements needed on report [Aparna]
- [x] Working session + brainstorm for other representations / visualisation types [ @Kabeer3 , Sumit @saurabhlevin ]
- [x] Prepare a mock-up (with design/layout in place)
- [x] Get feedback on mockup
- [x] Finalise template

**Comment by Deepthi-Chand** [comment]
Discussion scheduled with @Kabeer3 @saurabhlevin and Sumit

**Comment by aparnasr1** [comment]
Pick up a new issue when creating dynamic reports
