### ISSUE TITLE
UI changes (right data insights panel)

### ISSUE THREAD

**Issue by Deepthi-Chand** [CivicDataLab/IDS-DRR#25]
- [x] Add district name to RC
- [x] Work on hierarchy of titles and contents
- [x] Add a back button (back to prev. view feature)
- [x] Add link to datasets/superset (raw data explorer) - issue #3

**Comment by aparnasr1** [comment]
- [x] Get feedback on prototype

**Comment by aparnasr1** [comment]
Major changes being tested internally - closing this iteration. New changes tracked in #27
